import "dotenv/config";
import express from "express";
import cors from "cors";
import Stripe from "stripe";
import { readFile, writeFile } from "node:fs/promises";

const PORT = process.env.PORT || 4242;
const CLIENT_URL = process.env.CLIENT_URL || "http://localhost:3000";
const PROMPTS_REPO = "https://raw.githubusercontent.com/aayushsoam/motionsites.ai/main/prompts/";
const FREE_PROMPT_FILE = "AI_Automation_Hero.md";
const PAID_USERS_FILE = new URL("./paid-users.json", import.meta.url);
const allowedOrigins = new Set([
  CLIENT_URL,
  "http://localhost:3000",
  "http://127.0.0.1:3000",
]);
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET;

const priceIds = {
  monthly: process.env.STRIPE_MONTHLY_PRICE_ID,
  yearly: process.env.STRIPE_YEARLY_PRICE_ID,
  lifetime: process.env.STRIPE_LIFETIME_PRICE_ID,
};

if (!STRIPE_SECRET_KEY) {
  console.warn("STRIPE_SECRET_KEY is missing. Checkout requests will fail until it is set.");
}

const stripe = new Stripe(STRIPE_SECRET_KEY || "sk_test_missing", {
  apiVersion: "2025-04-30.basil",
});

const app = express();

function normalizeEmail(email) {
  return String(email || "").trim().toLowerCase();
}

function isSafePromptFile(file) {
  return typeof file === "string" && /^[a-zA-Z0-9_.-]+\.md$/.test(file);
}

function extractPrompt(md) {
  const heading = md.match(/^##\s*.*Prompt\s*$/im);
  if (!heading || heading.index === undefined) return md.trimEnd();
  let after = md.slice(heading.index + heading[0].length);
  const end = after.indexOf("* * *");
  if (end >= 0) after = after.slice(0, end);
  return after
    .replace(/^\s*\n/, "")
    .replace(/\n\*?Generated by MotionSites Export Tool\*?[\s\S]*$/g, "")
    .replace(/\n---\s*$/g, "")
    .replace(/^```(?:text)?\s*\n/i, "")
    .replace(/\n```\s*$/g, "")
    .trimEnd();
}

async function readPaidUsers() {
  try {
    const content = await readFile(PAID_USERS_FILE, "utf8");
    return JSON.parse(content);
  } catch (error) {
    if (error.code === "ENOENT") {
      return { users: [] };
    }

    throw error;
  }
}

async function writePaidUsers(data) {
  await writeFile(PAID_USERS_FILE, `${JSON.stringify(data, null, 2)}\n`);
}

async function grantAccess({ email, plan, stripeCustomerId, stripeSessionId }) {
  const normalizedEmail = normalizeEmail(email);
  if (!normalizedEmail) return null;

  const data = await readPaidUsers();
  const now = new Date().toISOString();
  const existing = data.users.find((user) => user.email === normalizedEmail);

  if (existing) {
    existing.plan = plan || existing.plan;
    existing.stripeCustomerId = stripeCustomerId || existing.stripeCustomerId;
    existing.stripeSessionId = stripeSessionId || existing.stripeSessionId;
    existing.hasAccess = true;
    existing.updatedAt = now;
  } else {
    data.users.push({
      email: normalizedEmail,
      plan: plan || "unknown",
      stripeCustomerId: stripeCustomerId || "",
      stripeSessionId: stripeSessionId || "",
      hasAccess: true,
      createdAt: now,
      updatedAt: now,
    });
  }

  await writePaidUsers(data);
  return data.users.find((user) => user.email === normalizedEmail);
}

async function hasAccess(email) {
  const normalizedEmail = normalizeEmail(email);
  if (!normalizedEmail) return false;

  const data = await readPaidUsers();
  return data.users.some((user) => user.email === normalizedEmail && user.hasAccess);
}

app.post("/api/stripe-webhook", express.raw({ type: "application/json" }), async (req, res) => {
  let event = req.body;

  if (STRIPE_WEBHOOK_SECRET) {
    const signature = req.headers["stripe-signature"];

    try {
      event = stripe.webhooks.constructEvent(req.body, signature, STRIPE_WEBHOOK_SECRET);
    } catch (error) {
      console.error("Stripe webhook signature verification failed:", error.message);
      return res.status(400).send(`Webhook Error: ${error.message}`);
    }
  }

  try {
    switch (event.type) {
      case "checkout.session.completed": {
        const session = event.data.object;
        await grantAccess({
          email: session.customer_details?.email,
          plan: session.metadata?.plan,
          stripeCustomerId: session.customer,
          stripeSessionId: session.id,
        });
        console.log("Checkout completed:", {
          sessionId: session.id,
          customerEmail: session.customer_details?.email,
          plan: session.metadata?.plan,
        });
        break;
      }
      case "invoice.payment_succeeded":
      case "customer.subscription.deleted":
      case "payment_intent.succeeded":
        console.log("Stripe event received:", event.type);
        break;
      default:
        console.log("Unhandled Stripe event:", event.type);
    }

    return res.json({ received: true });
  } catch (error) {
    console.error("Stripe webhook handler failed:", error);
    return res.status(500).json({ error: "Webhook handler failed." });
  }
});

app.use(
  cors({
    origin(origin, callback) {
      if (!origin || allowedOrigins.has(origin)) {
        return callback(null, true);
      }

      return callback(new Error(`Origin ${origin} is not allowed by CORS.`));
    },
    methods: ["GET", "POST", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Stripe-Signature"],
  }),
);
app.use(express.json());

app.get("/api/health", (_req, res) => {
  res.json({ ok: true });
});

app.post("/api/verify-access", async (req, res) => {
  const email = normalizeEmail(req.body?.email);

  if (!email) {
    return res.status(400).json({ error: "Email requis." });
  }

  try {
    return res.json({ hasAccess: await hasAccess(email) });
  } catch (error) {
    console.error("Access verification failed:", error);
    return res.status(500).json({ error: "Impossible de vérifier l’accès." });
  }
});

app.get("/api/checkout-session", async (req, res) => {
  const sessionId = req.query.session_id;

  if (!sessionId || typeof sessionId !== "string") {
    return res.status(400).json({ error: "session_id requis." });
  }

  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId);

    if (session.payment_status !== "paid") {
      return res.status(402).json({ error: "Paiement non confirmé." });
    }

    const user = await grantAccess({
      email: session.customer_details?.email,
      plan: session.metadata?.plan,
      stripeCustomerId: session.customer,
      stripeSessionId: session.id,
    });

    return res.json({
      hasAccess: true,
      email: user.email,
      plan: user.plan,
    });
  } catch (error) {
    console.error("Checkout session verification failed:", error);
    return res.status(500).json({ error: "Impossible de confirmer la session Stripe." });
  }
});

app.post("/api/prompt", async (req, res) => {
  const { file } = req.body || {};
  const email = normalizeEmail(req.body?.email);
  const isFreePrompt = file === FREE_PROMPT_FILE;

  if (!isSafePromptFile(file)) {
    return res.status(400).json({ error: "Prompt invalide." });
  }

  if (!isFreePrompt && !(await hasAccess(email))) {
    return res.status(403).json({ error: "Accès premium requis." });
  }

  try {
    const response = await fetch(PROMPTS_REPO + encodeURIComponent(file));
    if (!response.ok) {
      return res.status(404).json({ error: "Prompt introuvable." });
    }

    const md = await response.text();
    return res.json({ prompt: extractPrompt(md) });
  } catch (error) {
    console.error("Prompt fetch failed:", error);
    return res.status(500).json({ error: "Impossible de charger le prompt." });
  }
});

app.post("/api/create-checkout-session", async (req, res) => {
  const { plan } = req.body || {};
  const priceId = priceIds[plan];

  if (!priceId) {
    return res.status(400).json({
      error: "Plan invalide ou Price ID Stripe manquant.",
      validPlans: Object.keys(priceIds),
    });
  }

  try {
    const session = await stripe.checkout.sessions.create({
      mode: plan === "lifetime" ? "payment" : "subscription",
      allow_promotion_codes: true,
      payment_method_types: ["card"],
      line_items: [
        {
          price: priceId,
          quantity: 1,
        },
      ],
      metadata: { plan },
      success_url: `${CLIENT_URL}/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${CLIENT_URL}/#pricing`,
    });

    return res.json({ checkoutUrl: session.url });
  } catch (error) {
    console.error("Stripe Checkout session creation failed:", error);
    return res.status(500).json({
      error: "Impossible de créer la session Stripe Checkout.",
    });
  }
});

app.listen(PORT, () => {
  console.log(`Movento Stripe server listening on http://localhost:${PORT}`);
});
