import { Redis } from "@upstash/redis";
import Stripe from "stripe";

export const PROMPTS_REPO = "https://raw.githubusercontent.com/aayushsoam/motionsites.ai/main/prompts/";
export const CUSTOM_PROMPTS_REPO = "https://raw.githubusercontent.com/azoklearn/movento/main/prompts/";
export const FREE_PROMPT_FILES = new Set([]);

export const priceIds = {
  monthly: process.env.STRIPE_MONTHLY_PRICE_ID,
  yearly: process.env.STRIPE_YEARLY_PRICE_ID,
  lifetime: process.env.STRIPE_LIFETIME_PRICE_ID,
};

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || "sk_missing", {
  apiVersion: "2025-04-30.basil",
});

export function normalizeEmail(email) {
  // Strip every whitespace/zero-width char (mobile autocomplete can inject a
  // non-breaking or zero-width space that trim() leaves behind).
  return String(email || "").replace(/[\s\u200B-\u200D\uFEFF]/g, "").toLowerCase();
}

export function isSafePromptFile(file) {
  return typeof file === "string" && /^[a-zA-Z0-9_.-]+\.md$/.test(file);
}

export function getClientUrl(req) {
  const configured = process.env.CLIENT_URL || process.env.VERCEL_URL;
  if (configured) {
    return configured.startsWith("http") ? configured : `https://${configured}`;
  }

  const proto = req.headers["x-forwarded-proto"] || "https";
  return `${proto}://${req.headers.host}`;
}

export function extractPrompt(md) {
  const heading = md.match(/^##\s*.*Prompt\s*$/im);
  if (!heading || heading.index === undefined) return md.trimEnd();
  let after = md.slice(heading.index + heading[0].length);
  const end = after.indexOf("* * *");
  if (end >= 0) after = after.slice(0, end);
  return after
    .replace(/^\s*\n/, "")
    .replace(/\n\*?Generated by MotionSites Export Tool\*?[\s\S]*$/g, "")
    .replace(/\n---\s*$/g, "")
    .replace(/^```(?:text)?\s*\n/i, "")
    .replace(/\n```\s*$/g, "")
    .trimEnd();
}

export async function customerHasStripeAccess(email) {
  const normalizedEmail = normalizeEmail(email);
  if (!normalizedEmail) return false;

  try {
    const redis = Redis.fromEnv();
    const record = await redis.get(`access:${normalizedEmail}`);
    if (record) return true;
  } catch {
    // Redis not available, fall through to Stripe API
  }

  if (!process.env.STRIPE_SECRET_KEY) return false;

  try {
    const customers = await stripe.customers.list({ email: normalizedEmail, limit: 10 });

    const ACCESS_STATUSES = new Set(["active", "trialing", "past_due"]);

    for (const customer of customers.data) {
      const subscriptions = await stripe.subscriptions.list({
        customer: customer.id,
        status: "all",
        limit: 20,
      });
      if (subscriptions.data.some((s) => ACCESS_STATUSES.has(s.status))) return true;

      const charges = await stripe.charges.list({
        customer: customer.id,
        limit: 10,
      });
      if (charges.data.some((c) => c.paid && !c.refunded)) return true;
    }
  } catch (error) {
    console.error("Stripe customerHasStripeAccess error:", error);
    return false;
  }

  return false;
}

export function methodNotAllowed(res, allowed = "POST") {
  res.setHeader("Allow", allowed);
  return res.status(405).json({ error: "Méthode non autorisée." });
}
